brand:
  name: Tanken 
menu-string: Menu

nav:
  - title: Standpunten
    url: '#services'
  - title: Filmpje
    url: '#portfolio'
  - title: Activiteiten
    url: '#about'
  - title: Team
    url: '#team'
  - title: Contact
    url: '#contact'

copyright: Copyright &copy; Tanken 2019

social-buttons:
  - icon: fa fa-twitter
    url: '#' 
  - icon: fa fa-facebook
    url: '#'
  - icon: fa fa-linkedin
    url: '#'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
