intro:
  lead-in: "Broem broem!"
  heading: Lolploeg Tanken 
  btn: ik zen nen taaaank 

services:
  heading: Standpunten
  subheading: want tegenwoordig wordt ge verwacht een mening te hebben
  service:
    - icon: fa fa-laptop
      image: img/dumbbell.jpeg
      heading: Iedereen breed
      text: Als we niet dringend inzetten op de verbreding en de groei van de spieren, gaan we nooit ons streefdoel van 100% tankpopulatie bereiken. Bovendien wordt het vanaf volgend jaar verplicht een marcelleke te dragen, zodat ge uw gainz kunt blootstellen aan de wereld.
    - icon: fa fa-laptop
      image: img/fuel.jpg
      heading: Gratis brandstof voor iedereen
      text: De gele hesjes hebben gelijk. Brandstof bijvullen, oftewel tanken, is het beste dat er is. Tanken is een mensenrecht. Daarom opperen wij voor gratis brandstof voor iedereen. Niets zo belangrijk als een volle tank!
    - icon: fa fa-lock
      image: img/fish.svg
      heading: Vissen zwemmen niet langer in een bokaal
      text: Elke vis verdient een volwaardig huis met voldoende ruimte, elke vis heeft recht op een vistank.
    - icon: fa fa-lock
      image: img/cara.jpg
      heading: Behoud van de naam cara pils
      text: Wij vechten actief voor de naam van dit hemelse brouwsel, zodat we kunnen blijven pintjes tanken. 
    - icon: fa fa-lock
      image: img/cry.png
      heading: Verboden te janken
      text: In de plaats van uw traantjes te laten lopen, stellen wij voor dat u een pintje consumeert. De befaamde spreuk "ni janken, ma tanken" is niet enkel alombekend, het is levenswijsheid.
    - icon: fa fa-lock
      image: img/tank.svg
      heading: Iedereen een kanon op zijn voertuig en rupsbanden eronder
      text: Het is 2019. Hoe kunt ge op dit moment nog met een ouderwets voertuig zonder kanon rondrijden? Wat gaat ge doen als er een duif voor uw ruit vliegt? In ons geval, ne ké goe khnalle.

portfolio:
  heading: Filmpje
  subheading: Deze sequentie van foto's zal een duidelijk beeld scheppen over onze werking. Wordt verwacht op maandag 29 april.

about:
  heading: Activiteiten <br> DONDERDAG 9 MEI @ GRASVELD ALMA 3
  subheading: Ge wordt genen tank van in uwe zetel te blijven zitten.
  timeline:
    - image: img/about/1.jpg
      date: 
      title: Brakke site maken
      text: Ah nee das al gedaan

    - image: img/petank.jpg
      date:  
      title: Petanke
      text: Voor echte tanken hemme we ne petank

    - image: img/renolt.jpg
      date: 
      title: Renolt on display
      text: De renolt is al jaar en dag de grootste tank van ons land. Reeds meermaals bewees dit machien onverwoestbaar te zijn. Vandaag tunen we deze blitse kar opdat ie nog vele jaren kan blijven cruizen. 

    - image: img/cara.jpg
      date: 
      title: Ni janke ma tanke
      text: Rijkelijk zal de cara vloeien in jullie brandstoftankjes

    - image: img/stylo.jpg
      date: 
      title: Duzt gadgets
      text: Gadgets zijn nice. Shpeel en win.

    - image: img/sumo.jpg
      date: 
      title: Sumospelen
      text: De grootste tank wint

    - image: img/mitraillette.jpg
      date: 
      title: Mitraillettes eten
      text: Eigenlijk gewoon stokbrood me curryweste, frieten zijn te traag dus da doen we ni

    - image: img/milkshake.jpg
      date: 
      title: Shakeskes drinken
      text: Milkshakes wel, proteinenshakes zijn vuil

  end1: Wees
  end2: Een
  end3: Tank!

team:
  heading: Ons tankteam
  subheading: ne goeien tank rijdt ni alleen
  members:
    - name: Bobbie
      role: Oppertank
      img: img/team/robbert.jpg
        
    - name: Kobbe
      role: Vicetank
      img: img/team/jakob.jpg

    - name: Roel
      role: IT tank
      img: img/team/roeland.jpg

    - name: Ine
      role: Teletankie
      img: img/team/ine.jpg
        
    - name: Marte
      role: Biestank
      img: img/team/marte.jpg

    - name: Milan
      role: IT tank
      img: img/team/milan.jpg

    - name: Sander
      role: Vage tank
      img: img/team/sander.jpg

    - name: Matthias
      role: Techtank
      img: img/team/matthias.jpg
        
    - name: Helena
      role: Energetische ponytank
      img: img/team/helena.jpg

    - name: Alya
      role: Miss tank 2019
      img: img/team/ayla.jpg

    - name: Rutgi
      role: Net op tijdtank
      img: img/team/rutger.jpg

    - name: Ruben
      role: Sporttank
      img: img/team/ruben.jpg

    - name: Eline
      role: Nachtelijke tank
      img: img/team/eline.jpg

  text: + iedereen die ik vegeten ben 

clients:
  - img: img/tank1.png
    url: "#"
  - img: img/tank3.png
    url: "#"
  - img: img/tank4.png
    url: "#"
  - img: img/tank2.png   
    url: "#"

contact:
  heading: Contacteer Ons
  subheading: Maar niet via deze form.
  name: Your Name *
  name-required: Please enter your name.
  email: Your Email *
  email-required: Please enter your email address.
  phone: Your Phone *
  phone-required: Please enter your phone number.
  message: Your Message *
  message-required: Please enter a message.
  btn: Send Message

  js-url: '././mail/contact_me.php'
  js-success: 'Your message has been sent. '
  js-error: 'NI VIA DEZE FORM HAD IK GEZEGD'
  js-error-min: 'Sorry "+i+", it seems that my mail server is not responding. Please try again later!'
